"""Initial schema

Revision ID: d92438693fd2
Revises: 
Create Date: 2026-07-02 11:53:02.508170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92438693fd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_tags', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    # ### end Alembic commands ###
